### ISSUE TITLE
Drinks, eats and breathes CPU

### ISSUE THREAD

**Issue by HamletGhost** [dmnd/rainbow-selection#4]
When I have a selected area, an "Atom Helper" process uses a relevant fraction of CPU time (20 to 80%).

Select and copy a large area, go paste in another window, and in a while the fan will loudly tell your original area is still selected.

Seen on: OSX 10.10.5.

**Comment by dmnd** [comment]
I can reproduce that although my CPU time only increases to 40% or so.

Nevertheless, I'm going to close this issue. The CPU usage is likely a bug in Atom, not this extension. The source code is literally [a single CSS animation](https://github.com/dmnd/rainbow-selection/blob/master/styles/rainbow-selection.atom-text-editor.less). If that causes excessive resource consumption I recommend you report it as a bug in Atom core or just stop using the extension.
