### ISSUE TITLE
Deprecated selector in `rainbow-selection/styles/rainbow-selection.atom-text-editor.less`

### ISSUE THREAD

**Issue by diomat** [dmnd/rainbow-selection#5]
In `rainbow-selection/styles/rainbow-selection.atom-text-editor.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `:host .selection .region` => `atom-text-editor .selection .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by codyjk** [comment]
@dmnd any progress on this?

**Comment by tschwimmer** [comment]
@dmnd can we get an update here?

**Comment by diomat** [comment]
The fix is actually fairly simple but somehow I never looked into the less file :o  

Details in #6

**Comment by dmnd** [comment]
@codykrainock & @tschwimmer this is now fixed thanks to @diomat and his first ever PR on GitHub #6. Make sure to thank him! 🙇
