### ISSUE TITLE
[Not an issue, but a thanks!] I love this damn extension

### ISSUE THREAD

**Issue by MiracleBlue** [dmnd/rainbow-selection#7]
I don't know why, I just love it.  I install it on every instance of Atom I come into contact with.  The CPU hit used to be significant, but has since become almost unnoticeable recently, perhaps due to an Atom update, or perhaps my new Mac is a beast.  I dunno, even when that fan would start lifting my laptop into orbit, it was still worth it for the pretty colours.

Sorry for making an issue, I don't know of a better way to send such a message, but I've been using this plugin for a long time, I just had to do it.

Thanks for making it!

**Comment by dmnd** [comment]
Thank you for your kind message, @MiracleBlue! ❤️ 🌈
